# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'volume_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_volume_window(object):
    def setupUi(self, volume_window):
        volume_window.setObjectName("volume_window")
        volume_window.resize(373, 190)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(volume_window)
        self.verticalLayout_2.setContentsMargins(11, 11, -1, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Voxel_GroupBox = QtWidgets.QGroupBox(volume_window)
        self.Voxel_GroupBox.setObjectName("Voxel_GroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Voxel_GroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vsize_horizontalLayout = QtWidgets.QHBoxLayout()
        self.vsize_horizontalLayout.setObjectName("vsize_horizontalLayout")
        self.label = QtWidgets.QLabel(self.Voxel_GroupBox)
        self.label.setObjectName("label")
        self.vsize_horizontalLayout.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.Voxel_GroupBox)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(200)
        self.horizontalSlider.setProperty("value", 10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.vsize_horizontalLayout.addWidget(self.horizontalSlider)
        self.label_2 = QtWidgets.QLabel(self.Voxel_GroupBox)
        self.label_2.setObjectName("label_2")
        self.vsize_horizontalLayout.addWidget(self.label_2)
        self.vsize_horizontalLayout.setStretch(0, 2)
        self.vsize_horizontalLayout.setStretch(1, 7)
        self.vsize_horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.vsize_horizontalLayout)
        self.horizontalLayout_opacity = QtWidgets.QHBoxLayout()
        self.horizontalLayout_opacity.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_opacity.setSpacing(7)
        self.horizontalLayout_opacity.setObjectName("horizontalLayout_opacity")
        self.label_4 = QtWidgets.QLabel(self.Voxel_GroupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_opacity.addWidget(self.label_4)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Voxel_GroupBox)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 0.5)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_opacity.addWidget(self.doubleSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_opacity)
        self.verticalLayout_2.addWidget(self.Voxel_GroupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(volume_window)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(volume_window)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 6)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(volume_window)
        QtCore.QMetaObject.connectSlotsByName(volume_window)

    def retranslateUi(self, volume_window):
        _translate = QtCore.QCoreApplication.translate
        volume_window.setWindowTitle(_translate("volume_window", "Form"))
        self.Voxel_GroupBox.setTitle(_translate("volume_window", "Voxelize"))
        self.label.setText(_translate("volume_window", "Voxel Size"))
        self.label_2.setText(_translate("volume_window", "0.1"))
        self.label_4.setText(_translate("volume_window", "透明度"))
        self.pushButton.setText(_translate("volume_window", "绘制"))
        self.pushButton_2.setText(_translate("volume_window", "取消"))
